//file:noinspection UnnecessaryQualifiedReference
plugins {
    id 'java-library'
    id 'idea'
    // Forge/NeoForge cross with Architectury
    id 'dev.architectury.loom' version '1.7-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    // Shadow, needed to tie all configs together
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false

    // Adds the Kotlin Gradle plugin
    id 'org.jetbrains.kotlin.jvm' version "${kotlin_jvm_version}"
    // Kotlin Serialization plugin
    id 'org.jetbrains.kotlin.plugin.serialization' version "${kotlin_jvm_version}"
}

allprojects {

    version = rootProject.mod_version
    group = rootProject.mod_group_id

    compileKotlin.compilerOptions.jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21
    java.toolchain.languageVersion = JavaLanguageVersion.of(21)

}

architectury {
    minecraft = project.minecraft_version
    compileOnly()
}

subprojects {
    
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'
    
    base {
        archivesName = "${rootProject.mod_id}-${project.name}"
    }

    if (project.path != ':common') {
        loom {
            mods {
                main { // to match the default mod generated for Forge
                    sourceSet project.sourceSets.main
                    sourceSet project(':common').sourceSets.main
                }
            }
        }
    }

    // Include assets and data from data generators
    sourceSets.main.resources { srcDirs 'src/generated/resources/' }

    repositories {

        // maven for kotlin serialization
        maven {url = "https://kotlin.bintray.com/kotlinx"}

        maven {
            name = 'Kotlin for Forge'
            url = 'https://thedarkcolour.github.io/KotlinForForge/'
            content { includeGroup "thedarkcolour" }
        }

        // maven { url 'https://jitpack.io' } // use for BMApi [DEPRECATED]

        maven { url 'https://repo.bluecolored.de/releases' } // use for BMApi > 2.7.0
    }

    dependencies {
        
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"

        mappings loom.officialMojangMappings()

        /*mappings loom.layered {
            it.mappings("net.fabricmc:yarn:$rootProject.yarn_mappings:v2")
            it.mappings("dev.architectury:yarn-mappings-patch-neoforge:$rootProject.yarn_mappings_patch_neoforge_version")
        }*/

        // Kotlin Serialization JSON, because apparently the serialization plugin does not implement its dependency anymore
        implementation "org.jetbrains.kotlinx:kotlinx-serialization-core:${kotlin_json_version}"
        implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:${kotlin_json_version}"

        // compileOnly "com.github.BlueMap-Minecraft:BlueMapAPI:v${rootProject.bluemap_api_version}" // use for BMApi [DEPRECATED]

        // compileOnly "de.bluecolored.bluemap:BlueMapAPI:${rootProject.bluemap_api_version}" // use for BMApi ]2.7.0, 2.7.2] only

        compileOnly "de.bluecolored:bluemap-api:${rootProject.bluemap_api_version}" // use for BMApi >= 2.7.3
    }

    java {
        // Makes that sources AND remapped sources are BOTH generated
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21

    }

    def resourceTargets = ['META-INF/neoforge.mods.toml', 'META-INF/mods.toml', 'pack.mcmeta']
    def replaceProperties = [
            minecraft_version: rootProject.minecraft_version, minecraft_version_range: rootProject.minecraft_version_range,
            neo_version_range: rootProject.neo_version_range, forge_version_range: rootProject.forge_version_range,
            kff_version_range: rootProject.kff_version_range, bluemap_version_range: rootProject.bluemap_version_range,
            mod_id: rootProject.mod_id, mod_name: rootProject.mod_name, mod_license: rootProject.mod_license, mod_version: rootProject.mod_version,
            mod_authors: rootProject.mod_authors, mod_description: rootProject.mod_description, credits: rootProject.credits
    ]

    processResources {
        inputs.properties replaceProperties
        replaceProperties.put 'project', project

        filesMatching(resourceTargets) {
            expand replaceProperties
        }
    }

    compileKotlin.compilerOptions.jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21
    java.toolchain.languageVersion = JavaLanguageVersion.of(21)

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
        it.options.release = 21
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifact jar
            }
        }
        repositories {
            maven {
                url "file://${project.projectDir}/mcmodsrepo"
            }
        }
    }

    idea {
        module {
            downloadSources = true
            downloadJavadoc = true
        }
    }

}