modLoader="kotlinforforge"
loaderVersion="${kff_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="${credits}"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="SERVER"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="SERVER"
[[dependencies.${mod_id}]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="${kff_version_range}"
    ordering="NONE"
    side="SERVER"
[[dependencies.${mod_id}]]
    modId="bluemap"
    mandatory=true
    versionRange="${bluemap_version_range}"
    ordering="NONE"
    side="SERVER"
